name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        env:
            MY_EMAIL: kiran79bh@gmail.com
            MY_NAME: Kiran
        run: |
            git config --global user.email $MY_EMAIL
            git config --global user.name $MY_NAME
            git remote set-url origin https://$MY_NAME:${{ secrets.MY_PASSWORD }}@github.com/kiran079/kiran079.github.io.git
            npm run deploy
